# Generated by Django 6.0.1 on 2026-01-27 08:59

import banners.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='photos', validators=[banners.models.validate_image_size]),
        ),
    ]
