# Generated by Django 6.0.1 on 2026-01-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_logn_description',
            field=models.TextField(blank=True),
        ),
    ]
