# Generated by Django 6.0.1 on 2026-01-28 08:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price_logn_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_logn_description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
